#!/bin/bash
if command -v docker &> /dev/null; then
    echo "Docker is already installed"
    sudo usermod -aG docker $USER
else
    echo "Docker is not installed. Installing..."
    sudo dnf install docker -y
    sudo systemctl enable --now docker
    sudo usermod -aG docker $USER
fi
docker run -d \
  --name watchtower --restart always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e WATCHTOWER_CLEANUP=true \
  -e WATCHTOWER_POLL_INTERVAL=300 \
  -e DOCKER_API_VERSION=1.44 \
  containrrr/watchtower
